kind: PersistentVolume
apiVersion: v1
metadata:
  name: nfs-pv
  labels:
    volume: nfs-volume
    type: nfs
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    # TODO: modify path and server appropriately
    path: /mnt/disks/thinker-disk
    server: 10.146.15.198
